parameters:
#    martians.example.class: Martians\MartiansBundle\Example

services:
#    martians.example:
#        class: %martians.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
